In [1]:
import numpy as np

class KNN:
    def __init__(self, k=3):
        self.k = k

    def fit(self, X_train, y_train):
        self.X_train = X_train
        self.y_train = y_train

    def predict(self, X_test):
        predictions = []
        for x in X_test:
            distances = [np.linalg.norm(x - x_train) for x_train in self.X_train]
            k_indices = np.argsort(distances)[:self.k]
            k_nearest_labels = [self.y_train[i] for i in k_indices]
            most_common = max(set(k_nearest_labels), key=k_nearest_labels.count)
            predictions.append(most_common)
        return predictions


# Dataset 1

In [2]:
import pandas as pd

dataset = pd.read_csv("/content/project1_dataset1.txt", sep="\t")
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
x

array([[1.245e+01, 1.570e+01, 8.257e+01, ..., 1.741e-01, 3.985e-01,
        1.244e-01],
       [1.126e+01, 1.996e+01, 7.372e+01, ..., 9.314e-02, 2.955e-01,
        7.009e-02],
       [1.143e+01, 1.539e+01, 7.306e+01, ..., 8.476e-02, 2.676e-01,
        6.765e-02],
       ...,
       [1.450e+01, 1.089e+01, 9.428e+01, ..., 1.221e-01, 2.889e-01,
        8.006e-02],
       [1.236e+01, 1.854e+01, 7.901e+01, ..., 8.442e-02, 2.983e-01,
        7.185e-02],
       [1.193e+01, 2.153e+01, 7.653e+01, ..., 7.247e-02, 2.438e-01,
        8.541e-02]])

In [4]:
y

array([1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1, random_state = 1)

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [7]:
x_train

array([[ 0.99066707,  0.92372376,  1.11661305, ...,  1.2841721 ,
        -0.96350722,  2.09762058],
       [ 2.60015848,  1.69074393,  2.7529165 , ...,  2.3925318 ,
         0.48551869,  0.19672436],
       [ 1.54225024,  0.89616614,  1.52261315, ...,  1.02700859,
        -0.5192685 , -0.43727208],
       ...,
       [-1.02049004, -0.16020895, -1.02165417, ..., -0.73583978,
        -1.1056636 , -0.3061004 ],
       [ 0.24107968, -0.12346547,  0.24883908, ..., -0.45356147,
        -0.07341438,  0.44595055],
       [ 0.49565653,  1.06610475,  0.48915834, ..., -0.03473083,
        -0.14287716, -1.15598356]])

In [8]:
x_test

array([[-0.53396539, -1.1982123 , -0.53281364, ..., -0.34302627,
        -0.35611174,  0.23061038],
       [-0.61033845,  0.33353158, -0.57013284, ...,  0.01940885,
        -0.6985794 ,  0.86296717],
       [-0.81399992,  0.1268495 , -0.81332281, ..., -1.4134882 ,
         0.63736756, -1.02754463],
       ...,
       [-1.32739657,  0.54939954, -1.31938758, ..., -1.15060994,
        -0.04110611, -0.05359492],
       [-1.01483277,  0.86860853, -1.02206427, ..., -1.24761021,
        -1.08304782, -0.88817472],
       [-0.59619529,  1.2819727 , -0.58079547, ...,  0.09009122,
        -0.48211399, -0.082562  ]])

In [9]:
y_train

array([1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,

In [10]:
y_test

array([0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0])

In [11]:
classifier = KNN()

classifier.fit(x_train, y_train)

In [12]:
y_pred = classifier.predict(x_test)

In [13]:
print(y_pred)
# print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0]


In [14]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[34  0]
 [ 1 22]]


In [15]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def evaluate_model(X, y, model, n_splits=10):
    kf = []
    fold_size = len(X) // n_splits
    remainder = len(X) % n_splits
    start = 0
    for i in range(n_splits):
        if i < remainder:
            end = start + fold_size + 1
        else:
            end = start + fold_size
        test_indices = list(range(start, end))
        train_indices = list(set(range(len(X))) - set(test_indices))
        kf.append((train_indices, test_indices))
        start = end

    accuracy_scores = []
    precision_scores = []
    recall_scores = []
    f1_scores = []

    for train_index, test_index in kf:
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]

        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        accuracy_scores.append(accuracy_score(y_test, y_pred))
        precision_scores.append(precision_score(y_test, y_pred))
        recall_scores.append(recall_score(y_test, y_pred))
        f1_scores.append(f1_score(y_test, y_pred))

    print("Accuracy: {:.2f}".format(np.mean(accuracy_scores)))
    print("Precision: {:.2f}".format(np.mean(precision_scores)))
    print("Recall: {:.2f}".format(np.mean(recall_scores)))
    print("F1 Score: {:.2f}".format(np.mean(f1_scores)))

evaluate_model(x, y, classifier)

Accuracy: 0.93
Precision: 0.92
Recall: 0.87
F1 Score: 0.89


# Dataset 2

In [16]:
dataset = pd.read_csv("/content/project1_dataset2.txt", sep="\t")
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [17]:
x

array([[123, 0.05, 4.61, ..., 23.23, 2.78, 16],
       [128, 0.5, 3.7, ..., 21.25, 22.73, 28],
       [114, 9.6, 2.51, ..., 25.67, 40.63, 46],
       ...,
       [138, 4.5, 2.85, ..., 24.78, 24.89, 56],
       [170, 7.6, 5.5, ..., 37.41, 6.17, 54],
       [128, 0.0, 10.58, ..., 28.41, 14.66, 48]], dtype=object)

In [18]:
y

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,

In [19]:
x[:,4]

array(['Absent', 'Present', 'Absent', 'Present', 'Present', 'Absent',
       'Present', 'Absent', 'Present', 'Absent', 'Present', 'Absent',
       'Absent', 'Present', 'Present', 'Present', 'Present', 'Present',
       'Present', 'Absent', 'Present', 'Absent', 'Absent', 'Present',
       'Present', 'Present', 'Present', 'Absent', 'Present', 'Absent',
       'Present', 'Present', 'Absent', 'Absent', 'Present', 'Present',
       'Present', 'Absent', 'Absent', 'Absent', 'Absent', 'Absent',
       'Present', 'Absent', 'Absent', 'Absent', 'Absent', 'Absent',
       'Absent', 'Absent', 'Absent', 'Absent', 'Present', 'Absent',
       'Absent', 'Absent', 'Present', 'Present', 'Present', 'Absent',
       'Present', 'Absent', 'Present', 'Absent', 'Present', 'Present',
       'Absent', 'Absent', 'Absent', 'Present', 'Present', 'Absent',
       'Absent', 'Present', 'Present', 'Absent', 'Absent', 'Present',
       'Absent', 'Present', 'Absent', 'Absent', 'Present', 'Absent',
       'Absent', 'Prese

In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [4])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [21]:
x[:,4]

array([4.61, 3.7, 2.51, 6.38, 4.69, 10.53, 4.01, 6.53, 3.17, 9.78, 2.58,
       2.63, 4.82, 7.18, 6.57, 5.09, 2.66, 7.63, 5.73, 5.63, 5.11, 4.75,
       1.96, 4.9, 4.89, 4.67, 5.62, 1.87, 6.99, 3.47, 3.12, 8.53, 6.68,
       1.71, 3.36, 5.97, 2.19, 5.41, 4.91, 3.17, 5.46, 4.94, 4.89, 4.99,
       4.16, 6.08, 7.1, 3.89, 3.17, 7.32, 2.68, 5.56, 4.42, 4.22, 5.9,
       2.36, 8.41, 3.65, 4.55, 1.88, 4.79, 2.73, 6.23, 3.96, 3.59, 3.63,
       3.66, 5.59, 4.68, 2.44, 7.22, 3.69, 3.84, 4.18, 3.2, 14.16, 3.98,
       2.44, 3.66, 6.26, 3.38, 5.9, 7.85, 1.82, 1.77, 8.46, 2.85, 3.57,
       6.63, 3.54, 8.29, 3.16, 4.9, 2.81, 6.33, 6.09, 3.22, 10.49, 3.68,
       1.96, 2.83, 4.14, 8.49, 11.17, 9.19, 1.86, 5.29, 5.04, 5.08, 6.41,
       7.04, 3.3, 2.05, 2.96, 2.51, 2.8, 3.24, 5.05, 2.28, 3.58, 5.59,
       3.52, 6.22, 6.13, 8.12, 3.02, 5.21, 5.35, 2.82, 5.05, 4.43, 5.32,
       3.57, 8.28, 6.65, 4.37, 1.07, 4.8, 1.94, 3.14, 3.95, 4.66, 3.26,
       6.41, 2.43, 1.88, 12.42, 6.06, 8.12, 6.58, 4.31, 5

In [22]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1, random_state = 1)

In [23]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [25]:
classifier = KNN()

classifier.fit(x_train, y_train)

In [26]:
y_pred = classifier.predict(x_test)

In [27]:
print(y_pred)

[1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0]


In [28]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[22  2]
 [11 12]]


In [29]:
evaluate_model(x, y, classifier)

Accuracy: 0.57
Precision: 0.38
Recall: 0.32
F1 Score: 0.33
